# Generated by Django 5.0.6 on 2024-06-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(help_text='subjectName is required', max_length=120)),
                ('subjectCode', models.CharField(help_text='subjectCode is required', max_length=120, unique=True)),
                ('numberOfClasses', models.BigIntegerField(help_text='numberOfClasses is required')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
