# Generated by Django 5.0.6 on 2024-06-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_subject_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, help_text='fullName field is required', max_length=120, null=True)),
                ('email', models.EmailField(blank=True, help_text='email field is required', max_length=254, null=True, unique=True)),
                ('phoneNumber', models.CharField(blank=True, help_text='phoneNumber field is required', max_length=15, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
