# Generated by Django 5.0.6 on 2024-06-20 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_teacher_alter_student_fullname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='group',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.OneToOneField(help_text='student is required', on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
