# Generated by Django 5.0.6 on 2024-06-20 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_teacher_group_active_alter_group_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(help_text='student is required', related_name='student_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
