# Generated by Django 5.0.6 on 2024-06-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_group_students_group_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(help_text='course field is required', max_length=255, null=True),
        ),
    ]
