# Generated by Django 5.0.6 on 2024-06-21 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='date is required')),
                ('present', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('groupId', models.ForeignKey(help_text='groupId is Required', on_delete=django.db.models.deletion.CASCADE, to='app.group')),
                ('studentId', models.ForeignKey(help_text='studentID is required', on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
