# Generated by Django 5.0.6 on 2024-06-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullName', models.CharField(help_text='Full name is required', max_length=255)),
                ('email', models.EmailField(help_text='Email field is required', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Enter your password', max_length=50)),
                ('course', models.CharField(help_text='Course is required', max_length=255)),
                ('phoneNumber', models.CharField(help_text='Phone number is required', max_length=14)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Admin')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
