# Generated by Django 5.0.6 on 2024-06-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullName', models.CharField(default='Ram Khadka', help_text='Enter your full name', max_length=200)),
                ('email', models.EmailField(help_text='Enter your Email', max_length=255, unique=True, verbose_name='Email')),
                ('password', models.CharField(help_text='Enter your password', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('phoneNumber', models.CharField(max_length=14, null=True, unique=True)),
                ('role', models.CharField(choices=[('teacher', 'teacher'), ('admin', 'admin')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
