# Generated by Django 5.0.6 on 2024-06-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullName', models.CharField(help_text='fullName is required', max_length=255)),
                ('email', models.EmailField(blank='False', help_text='email field required', max_length=254, null='False', unique=True)),
                ('password', models.CharField(blank='False', help_text='enter your password', max_length=50, null='False')),
                ('course', models.CharField(help_text='course is required', max_length=255)),
                ('phoneNumber', models.CharField(help_text='phone number is required', max_length=14)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Admin')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
