# Generated by Django 5.0.6 on 2024-06-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='course',
        ),
        migrations.RemoveField(
            model_name='users',
            name='created',
        ),
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='users',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='users',
            name='updated',
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(help_text='Enter your Email', max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(help_text='Enter your password', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='fullname',
            field=models.CharField(default='Ram Khadka', help_text='Enter your full name', max_length=200),
        ),
    ]
