# Generated by Django 5.0.6 on 2024-06-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_fullname_users_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='full_name',
            new_name='fullName',
        ),
    ]
