# Generated by Django 5.0.6 on 2024-06-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_users_course_remove_users_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='fullname',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
